#!/bin/bash

# Update system
# kudos: http://osxdaily.com/2012/12/05/9-command-line-tricks-for-mac-os-x-you-should-know/
echo "I'll try to update your Mac now. You need to be logged in into Mac App Store. You'll be prompted for your user's password (not the app store password!)"
echo "5s to abort."
sleep 5
sudo softwareupdate -i -a

# Install San Francisco Font
# kudos: https://github.com/supermarin/YosemiteSanFranciscoFont
ruby -e "$(curl -fsSL https://raw.github.com/supermarin/YosemiteSanFranciscoFont/master/install)"

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install software from homebrew
brew install pwgen
brew install vim
brew install youtube-dl
brew install bash-completion
brew install csshx
brew install graphviz
brew install mtr
brew install wget
brew install htop-osx
brew install mobile-shell
brew install nmap
brew install sipcalc
brew install tmux
brew install tcptraceroute

# Install brew cask
brew install caskroom/cask/brew-cask

# Install software from cask
brew cask install dropbox
brew cask install google-chrome
brew cask install firefox
brew cask install adium
brew cask install skype

# Checkout all my github repos
mkdir ~/git
cd ~/git
for i in $(wget -q -O- https://github.com/tuxpeople?tab=repositories | grep tuxpeople | grep Forks | awk '{ print $5 }' | cut -d'/' -f3)
do
  git clone https://github.com/tuxpeople/$i.git
done
