#!/bin/bash

# Update system
# kudos: http://osxdaily.com/2012/12/05/9-command-line-tricks-for-mac-os-x-you-should-know/
echo "I'll try to update your Mac now. You need to be logged in into Mac App Store. You'll be prompted for your user's password (not the app store password!)"
echo "5s to abort."
sleep 5
sudo softwareupdate -i -a

# Install San Francisco Font
# kudos: https://github.com/supermarin/YosemiteSanFranciscoFont
#ruby -e "$(curl -fsSL https://raw.github.com/supermarin/YosemiteSanFranciscoFont/master/install)"

# Check for Homebrew,
# Install if we don't have it
if test ! $(which brew); then
 echo "Installing homebrew..."
 ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# add caskroom
brew tap caskroom/cask

# Update homebrew recipes
brew update

# Install software from homebrew
binaries=(
 pwgen
 vim
 youtube-dl
 bash-completion
 csshx
 graphviz
 mtr
 wget
 htop-osx
 mobile-shell
 nmap
 sipcalc
 tmux
 tcptraceroute
 fping
 apt-dater
 arping
 webkit2png
 keybase
 links
 lynx
# sshfs
 tree
 trash
 homebrew/dupes/whois
 mas
 rclone
)

echo "Installing homebrew software..."
brew install ${binaries[@]}

# Install software from cask
apps=(
 dropbox
 google-chrome
 firefox
 adium
 skype
 cakebrew
 darktable
 franz
 caskroom/versions/microsoft-office-2011
 xquartz
 little-snitch
 )

# Install apps to /Applications
# Default is: /Users/$user/Applications
echo "Installing apps from cask..."
brew cask install ${apps[@]}

# Add tap and install libvirt-manager
# See also https://github.com/jeffreywildman/homebrew-virt-manager for info
brew tap jeffreywildman/homebrew-virt-manager
brew install virt-manager virt-viewer

# Cask fonts
brew tap caskroom/fonts

# fonts
fonts=(
  font-roboto
)

# install fonts
echo "installing fonts..."
brew cask install ${fonts[@]}

# Cleanup...
brew cleanup

# Install MAS software
# List:
# 
# 443987910 1Password - Password Manager and Secure Wallet
# 410968114 PDFScanner - Simple document scanning and OCR
# 824183456 Affinity Photo
# 404010395 TextWrangler
# 409789998 Twitter
# 671736912 FruitJuice - Active Battery Health and Monitoring
# 410628904 Wunderlist: To-Do List & Tasks
# 407963104 Pixelmator
# 897814548 Cellist: HTTP debugging proxy

masapps=(
  443987910
  410968114
  824183456
  404010395
  409789998
  671736912
  410628904
  407963104
  897814548
)

# Install:
mas install ${masapps[@]}

# Checkout all my github repos
mkdir ~/git
cd ~/git
for i in $(wget -q -O- https://github.com/tuxpeople?tab=repositories | grep tuxpeople | grep Forks | awk '{ print $5 }' | cut -d'/' -f3)
do
  git clone git@github.com:tuxpeople/$i.git
done

# Add my Dropbox "bin" folder to path
echo "export PATH=$PATH:~/Dropbox/Allgemein/bin" >> .profile

